apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-console-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-console-consumer
  template:
    metadata:
      labels:
        app: kafka-console-consumer
    spec:
      containers:
        - name: kafka-console-consumer
          image: docker.io/sebgot/kafka-console-consumer:0.0.2
          imagePullPolicy: IfNotPresent
          env:
            - name: BOOTSTRAP
              value: "KAFKA-KAFKA-BOOTSTRAP:9092"
            - name: TOPIC_NAME
              value: "onprem.utv.doc-examples.data.add.v1"
            - name: CONSUMER_GROUP
              value: "team-2s-canary"
            - name: SASL_CLIENT_ID
              value: "team-2s"
            - name: SASL_CLIENT_SECRET
              value: "1234"
            - name: SASL_TOKEN_ENDPOINT_URL
              value: "http://keycloak.keycloak.svc.cluster.local:8080/realms/master/protocol/openid-connect/token"
            - name: SASL_AUDIENCE
              value: "kafka"

          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
